### PR TITLE
Add remap and InvLerp

### PR DESCRIPTION
**Pull request by TaRosh**

### CODE REVIEW

**Comment by quasilyte** [comment]
I never used remap and inverse lerp, so I Googled a bit.

Looks like the remap was known as `range_lerp` some time ago, but now it's `remap`:
https://github.com/godotengine/godot/pull/65361

I wonder whether `InvLerp` should be `InverseLerp` to fit the Godot naming, but I personally prefer the shorter form because Go math expressions are usually verbose enough anyway.

But for the context and searchability, I may add a comment to the code later.

* `inverse_lerp`: https://github.com/godotengine/godot/blob/d0dc3896ad6fe039e4ad0607d901c81197cb3a3b/core/math/math_funcs.h#L437
* `remap`: https://github.com/godotengine/godot/blob/d0dc3896ad6fe039e4ad0607d901c81197cb3a3b/core/math/math_funcs.h#L444

**Comment by quasilyte** [comment]
I would like an empty line between the function declarations, but it's something I can fix myself in a follow-up.
Thank you for the contribution!

Feel free to submit tests or other functions in the future! :)

**Review by quasilyte — APPROVED** [review]

**Comment by quasilyte** [comment]
Here is a follow-up:
https://github.com/quasilyte/gmath/commit/8e177b514b9189c1dc544d5c8fbec9c3aa74ddfd

**Comment by TaRosh** [comment]
Thanks! I start using ebitengine after your article and find this functions useful when u wanna map entity position to something else ( hue values or hp value ). I'm not good at coding, so can't contribut much (.__. )

**Pull request merged**
